sources:
- name: pubmed
  type: api
  format: xml
  #source url - the adress to which the api calls will be made. For pubmed, we will use the eutils api
  # source API- the differnt endpoints inside source url. For pubmed, we will use the esearch and efetch endpoints to retrieve data
  base_url: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/

  text_field: AbstractText
  rate_limit: 3
  id_field: PMID
  api_key_env: PUBMED_API_KEY
  search_query: ''
- name: geo
  type: api
  format: xml
  base_url: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/
  text_field: null
  rate_limit: 3
  id_field: GSE
  api_key_env: GEO_API_KEY
  search_query: ''
- name: pmc
  type: api
  format: xml
  base_url: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/
  text_field: null
  rate_limit: 3
  id_field: PMCID
  api_key_env: PUBMED_API_KEY
  search_query: ''
- name: clinicaltrials
  type: api
  format: json
  base_url: https://clinicaltrials.gov/api/v2/studies/
  text_field: null
  rate_limit: 5
  id_field: nctId
  search_query: ''
- name: biorxiv
  type: api
  format: json
  base_url: https://api.biorxiv.org/details/biorxiv/
  text_field: abstract
  rate_limit: 5
  id_field: doi
  search_query: ''
- name: pdf
  type: file
  format: pdf
  base_url: null
  text_field: null
  rate_limit: null
  id_field: null
  search_query: null
  watch_dir: data/pdf_inbox
- name: www.medrxiv.org
  type: api
  format: pdf
  base_url: https://www.medrxiv.org/
  text_field: null
  rate_limit: null
  id_field: null
  search_query: null
