"""Layer 8 Output A — writes validated relations to Neo4j-importable CSV + Cypher files."""
import csv
import os
import re
from collections import defaultdict
from pathlib import Path


_OUT_DIR   = Path(os.getenv("NEO4J_OUTPUT_DIR", "data/output/neo4j"))
_DELIMITER = "|"


def _slug(text: str) -> str:
    """Convert to lowercase underscore slug for use in filenames."""
    return re.sub(r"[^a-z0-9]+", "_", (text or "other").lower()).strip("_")


def write(records: list, run_dir: Path = None) -> dict:
    """Write all records to Neo4j CSV and Cypher files under run_dir/neo4j/."""
    out_dir = (run_dir / "neo4j") if run_dir else _OUT_DIR
    out_dir.mkdir(parents=True, exist_ok=True)

    # ── Collect unique nodes ──────────────────────────────────────────────────
    # {entity_type_slug: {canonical_id: row_dict}}
    nodes: dict = defaultdict(dict)

    for r in records:
        for name_key, type_key, id_key, src_key, review_key in [
            ("subject_name", "subject_type", "subject_id",
             "subject_id_source", "subject_needs_review"),
            ("object_name",  "object_type",  "object_id",
             "object_id_source", "object_needs_review"),
        ]:
            cid   = r.get(id_key, "") or ""
            name  = r.get(name_key, "") or ""
            etype = r.get(type_key, "OTHER") or "OTHER"
            slug  = _slug(etype)

            if cid and cid not in nodes[slug]:
                nodes[slug][cid] = {
                    "id":           cid,
                    "name":         name,
                    "entity_type":  etype,
                    "id_source":    r.get(src_key, "") or "",
                    "needs_review": str(r.get(review_key, False)).lower(),
                }

    # ── Group edges by (source_type, relation, target_type) — NO duplication ────
    # Edge goes in the SOURCE entity type's folder with a descriptive filename.
    #   protein inhibits gene     → protein/edges_protein_inhibits_gene.csv
    #   gene    regulates protein → gene/edges_gene_regulates_protein.csv
    # {source_slug: {(relation_slug, target_slug): [record, ...]}}
    edge_groups: dict = defaultdict(lambda: defaultdict(list))
    for r in records:
        s_slug = _slug(r.get("subject_type", "OTHER") or "OTHER")
        o_slug = _slug(r.get("object_type",  "OTHER") or "OTHER")
        rel    = _slug(r.get("relation", "related_to") or "related_to")
        edge_groups[s_slug][(rel, o_slug)].append(r)

    # ── Write one folder per entity type ─────────────────────────────────────
    # neo4j/{entity_type}/
    #   nodes_{entity_type}.csv       ← all nodes of this type
    #   edges_{relation}.csv          ← edges where THIS type is the source
    node_fields = ["id", "name", "entity_type", "id_source", "needs_review"]
    node_files: list = []
    all_slugs = sorted(set(nodes.keys()) | set(edge_groups.keys()))

    for slug in all_slugs:
        type_dir = out_dir / slug
        type_dir.mkdir(parents=True, exist_ok=True)

        # Node file
        if slug in nodes:
            csv_path    = type_dir / f"nodes_{slug}.csv"
            cypher_path = type_dir / f"nodes_{slug}.cypher"
            with open(csv_path, "w", newline="", encoding="utf-8") as f:
                w = csv.DictWriter(f, fieldnames=node_fields,
                                   delimiter=_DELIMITER, extrasaction="ignore")
                w.writeheader()
                for row in nodes[slug].values():
                    w.writerow(row)
            _write_node_cypher(slug, csv_path, cypher_path, out_dir)
            node_files.append(str(csv_path))

    return {
        "output_dir":  str(out_dir),
        "node_files":  node_files,
        "edge_files":  [],
        "node_types":  list(nodes.keys()),
        "edge_types":  [],
        "node_count":  sum(len(v) for v in nodes.values()),
        "edge_count":  0,
    }


def _write_node_cypher(label: str, csv_path: Path, cypher_path: Path, out_dir: Path) -> None:
    relative = csv_path.relative_to(out_dir).as_posix()
    query = f"""// nodes_{label}.cypher — generated by bio-semantic-parser Layer 8
CREATE CONSTRAINT IF NOT EXISTS FOR (n:{label}) REQUIRE n.id IS UNIQUE;

CALL apoc.periodic.iterate(
    "LOAD CSV WITH HEADERS FROM 'file:///{relative}' AS row FIELDTERMINATOR '{_DELIMITER}' RETURN row",
    "MERGE (n:{label} {{id: row.id}})
     SET n.name         = row.name,
         n.entity_type  = row.entity_type,
         n.id_source    = row.id_source,
         n.needs_review = row.needs_review",
    {{batchSize: 1000, parallel: true}}
)
YIELD batches, total
RETURN batches, total;
"""
    cypher_path.write_text(query, encoding="utf-8")
